{{- if .Values.init.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "superset.fullname" . }}-init-db
  labels:
    app: {{ include "superset.name" . }}
    chart: {{ include "superset.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ttlSecondsAfterFinished: 100
  template:
    metadata:
      name: {{ include "superset.fullname" . }}-init-db
      labels:
        app: {{ include "superset.name" . }}
        chart: {{ include "superset.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
      annotations:
        checksum/secrets: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with .Values.deploymentAnnotations }}
        {{- . | toYaml | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "superset.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: superset-configs
          secret:
            secretName: {{ include "superset.fullname" . }}
        - name: storage-volume
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "superset.fullname" .) }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: {{ include "superset.fullname" . }}-encrypted-secrets
          configMap:
            name: {{ include "superset.fullname" . }}-cm
        - name: {{ include "superset.fullname" . }}-decrypted-secrets
          emptyDir:
            medium: Memory
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.image.pullSecrets | indent 8 }}
      {{- end }}
      {{- if .Values.enableKamusSecrets }}
      initContainers:
        - name: "kamus-init"
          image: "soluto/kamus-init-container:latest"
          imagePullPolicy: IfNotPresent
          env:
            - name: KAMUS_URL
              value: http://kamus-decryptor.default.svc.cluster.local/
          volumeMounts:
            - name: {{ include "superset.fullname" . }}-encrypted-secrets
              mountPath: /encrypted-secrets
            - name: {{ include "superset.fullname" . }}-decrypted-secrets
              mountPath: /decrypted-secrets
          args: ["-e","/encrypted-secrets","-d","/decrypted-secrets", "-n", "superset_config.json"]
          {{- with .Values.init.resources }}
          resources:
            {{- . | toYaml | nindent 12 }}
          {{- end }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/usr/bin/env"]
          args:
          - bash
          - /home/superset/init_superset_db.sh
          {{- range .Values.init.extraArguments }}
          - {{ . }}
          {{- end }}
          {{- range .Values.init.extraSecureArguments }}
          - {{ . }}
          {{- end }}
          volumeMounts:
            - name: superset-configs
              mountPath: /home/superset
            - name: storage-volume
              mountPath: /var/lib/superset
            - name: {{ include "superset.fullname" . }}-decrypted-secrets
              mountPath: /secrets
          {{- if .Values.extraEnv }}
          env:
            {{- range $key, $value := .Values.extraEnv }}
            - name: "{{ $key }}"
              value: "{{ $value }}"
            {{- end }}
          {{- end }}
          {{- if .Values.extraEnvFromSecret }}
          envFrom:
            - secretRef:
                name: {{ .Values.extraEnvFromSecret }}
          {{- end }}
          {{- with .Values.init.resources }}
          resources:
            {{- . | toYaml | nindent 12 }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.init.securityContext | nindent 12 }}
      restartPolicy: Never
{{- end }}
