{{- if .Values.pdb.enabled }}
{{- if semverCompare "<1.21-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: "policy/v1beta1"
{{- else -}}
apiVersion: "policy/v1"
{{- end -}}
kind: PodDisruptionBudget
metadata:
  name: {{ include "superset.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "superset.name" . }}
    chart: {{ include "superset.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  {{- if .Values.pdb.minAvailable }}
  minAvailable: {{ .Values.pdb.minAvailable }}
  {{- end }}
  {{- if .Values.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ include "superset.name" . }}
      chart: {{ include "superset.chart" . }}
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
{{- end }}
